### ISSUE TITLE
Can you update this to the latest version 3.0.0-ALPHA11

### ISSUE THREAD

**Issue by brexmania123** [Falkirks/iControlU#6] opened 2018-02-07 19:54 UTC
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11

**Comment by falkirks** [comment] 2018-02-07 20:27
Duplicate of #2

**Closed as completed** 2018-02-07 20:27 UTC
Labels: duplicate
